markdown: kramdown
permalink: pretty
plugins:
  - jekyll-feed
  - jekyll-default-layout

collections:
  opinions:
    output: true
  resources:
    output: true
  conversations:
    output: true

defaults:
  - scope:
      path: ""
      type: opinions
    values:
      layout: opinion
