markdown: kramdown
permalink: pretty
plugins:
  - jekyll-feed
  - jekyll-default-layout

collections:
  opinions:
    output: true
  resources:
    output: true
  conversations:
    output: true
  letters:
    output: true

defaults:
  - scope:
      path: ""
      type: opinions
    values:
      layout: opinion
  - scope:
      path: ""
      type: resources
    values:
      layout: default
  - scope:
      path: ""
      type: letters
    values:
      permalink: /letters/:year/:title/
      layout: default
